<?php

namespace KLS\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends EntityRepository
{
    public function getSlider()
    {
        $qb = $this->createQueryBuilder('g')
                    ->join('g.image', 'i')
                    ->where('g.position != 0');

        return $qb->getQuery()->getResult();
    }

    public function findByPosition($position)
    {
        $qb = $this->createQueryBuilder('g')
            ->where('g.position = :position')
            ->setParameter('position', $position)
            ->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
