<?php

namespace KLS\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    public function findByPosition($position)
    {
        $qb = $this->createQueryBuilder('m')
            ->where('m.position = :position')
            ->setParameter('position', $position)
            ->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getRecipes($max)
    {
        $qb = $this->createQueryBuilder('m')
                ->join('m.image', 'i')
                ->where('m.position != 0')
                ->setMaxResults($max);

        return $qb->getQuery()->getResult();
    }
}
