<?php

namespace KLS\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PressRepository extends EntityRepository
{
    public function getOneRandom()
    {
        $count = $this->createQueryBuilder('p')
                        ->select('p.id');

        $ids = $count->getQuery()->getArrayResult();

        if (empty($ids)) {
            return null;
        }

        $index = array_rand($ids);

        $id = $ids[$index]['id'];

        $qb = $this->createQueryBuilder('p')
                    ->where('p.id = :id')
                    ->setParameter('id', $id)
                    ->setMaxResults(1);

        return $qb->getQuery()->getSingleResult();
    }
}
