<?php

namespace KLS\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VariableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariableRepository extends EntityRepository
{
    public function getValue($name, $default = null)
    {
        $variable = $this->getByName($name);

        if (null === $variable)
            return $default;
        else
            return $variable->getValue();
    }

    public function getByName($name)
    {
        $qb = $this->createQueryBuilder('v')
            ->where('v.name = :name')
            ->setParameter('name', $name);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
